export const Messages = {
    OK : "OK",
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    USER_BLOCKED: "Your are blocked from TicketFlow, Please contact support",
    USER_NOT_FOUND: "User not found !",
    OTP_ERROR: "Error while sending OTP, Try again later",
    OTP_RESENT: "OTP has been resent successfully",
    OTP_EXPIRED: "Your OTP has been expired, try again",
    INCORRECT_OTP: "The OTP you provided is incorrect",
    OTP_VERIFIED: "OTP verification successful",
    EMAIL_AND_OTP : "Provide Email and OTP to Continue !",
    NO_ACCESS: "Unauthorized Access",
    INVALID_REQUEST: "Invalid request",
    INVALID_CREDENTIALS: "Invalid Credentials",
    ALL_FILED_REQUIRED_ERR : "Provide all required fields and valid input",
    VERIFIED_EMAIL_ERR : "Provide Verified Email ID",
    FAIL_TRY_AGAIN : "Operation failed Try again !",
    REGISTER_SUCCESS: "Registraction successfull !",
    LOGIN_SUCCESS : "Login was successfull !",
    TOKEN_NOT_FOUND : "Token not found ! Please Try to login again!",
    TOKEN_INVALID : "Token invalid or not found !",
    TOKEN_EXPIRED : "Token is invalid or expired",
    EMAIL_MISSING :  "Provide email",
    USER_UPDATE_FAILED : "User update failed ! Please Try again",
    USER_UPDATE_SUCCESS : "User status update successfully",
    EMAIL_INVALID : "email is invalid or not found !",
    FORGOT_PASS_LINK : "change password link sended to email",
    INVALID_FIELDS : "Invalid fileds , or missing some field !",
    PASSWORD_UPDATED : "Password updated , login with new credentials",
    PASSWORD_NOT_MATCHING : "Current password is not matching !",
    INPUT_INVALID_OR_MISSING_SOME_FIELD : "Given input are invalid or some of fields are missing ! try again",
    SOMETHING_WENT_WRONG : "Something went wrong try again later",
    DATA_NOT_FOUND : "requested data not found",
    PAYLOAD_NOT_FOUND : "Payload data not found!",
    EMAIL_STORED_AND_CONTINUE : "successfull, fill the form to continue",
    OPERATION_ROLLBACKED  : "Failed to save data in CS DB, user data rollbacked ", 
    FIRST_LOGIN_SUCCESS : "Login successfull. Reset your password and continue !",
    REGISTRATION_IN_PROGRESS :  "User registration already in progress",
    OTP_SENDED : "Kindly check your email for OTP ",
    UPDATE_PASS_FAILED : "update password was failed ! retry again",
    UPDATE_PASS_SUCCESS : "successfully updated password ! kindly login with new credentials",
    LOGOUT_SUCCESS  : "logout successfully!",
    ROUTE_WILD_CARD_MESSAGE : "Endpoint not found. Please check the URL.",

  };
  