export const Messages = {
    SERVER_ERROR: "Internel server error",
    NO_ACCESS: "Unauthorized Access",
    INVALID_REQUEST: "Invalid request",
    ALL_FILED_REQUIRED_ERR : "Provide all required fields",
    FAIL_TRY_AGAIN : "Operation failed Try again !",
    DATA_NOT_FOUND : "Requested data not found !",
    FETCH_SUCCESS : "Data fetched successfully !" ,
    ENTER_VALID_INPUT : "Enter valid input !",
    EMAIL_INVALID : "Email ID is invalid",
    REQUIRED_FIELD_MISSING : "Required fields are missing",
    DATA_CREATED : "data created successfully",
    FILE_UPDATED : "File updated successfully",
    INVALID_INPUT : "Enter valid Inputs fields",
    INVALID_FILED_OR_MISSING_FIELD : "Invalid fields or missing required fields !",
    ERROR_PUBLISH_MSSG :  "Error in publishing the message to queue !",
    CHANNEL_NOT_AVILABLE :  "Channle is not avilable",
    SOMETHING_WRONG : "Something went wrong ! please try again",
    ERROR_WHILE : "❌ Error while processing  ",
    SESSION_SUCCESS : "Session created successfully",
    WEBHOOK_SIGN_FAIL : "Webhook signature verification failed",
    VERIFICATION_FAIL : "verification failed !",
    METADATA_MISSING : "metadata is missing",
    PURCHASE_SUCCESS : "Purchase verified successfully",
    ORDER_SAVING_FAILED : "Something went wrong in order saving , please try again",
    TOKEN_INVALID : "Token invalid or not found !",
    SESSION_ID_MISSING : "Payment referece is missing , try after some time",
    DATABASE_CONNECT_SUCCESS : "🚀 Database connnection established !!",
    DATABASE_CONNECT_FAIL : "❌ Database connnection establishion failed !!",
    START_SERVER_ERROR : "❌ Error starting server:",
    USER_BLOCKED: "Your are blocked from TicketFlow, Please contact support",
    ROUTE_WILD_CARD_MESSAGE : "Endpoint not found. Please check the URL.",

  } as const;
  