#version: '3.9'


services:

  # Logging Services
  loki:
    image: grafana/loki:2.9.0
    container_name: ticketflow-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - ticketFlow-internal
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 750M
        reservations:
          cpus: '0.2'
          memory: 500M
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://ticketflow-loki:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
   

  
  grafana:
    image: grafana/grafana:10.2.3
    container_name: ticketflow-grafana
    ports:
      - "3600:3000"
    env_file:
      - .env.grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards 
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 400M
        reservations:
          cpus: '0.15'
          memory: 200M
    depends_on:
      loki:
        condition: service_healthy
    networks:
      - ticketFlow-internal
      - ticketFlow-external
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --no-verbose --tries=1 --spider http://ticketflow-grafana:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticketflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 800M
        reservations:
          cpus: '0.2'
          memory: 400M
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ticketFlow-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD","rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s

  

  redis:
    image: redis:7.2.4-alpine
    container_name: ticketFlow-redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
        reservations:
          cpus: '0.15'
          memory: 150M
    command: ["redis-server" , "--appendonly" , "yes"]
    volumes:
      - redis_data:/data
    networks:
      - ticketFlow-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
  


  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    container_name: ticketFlow-apiGateway
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
      - ./api-gateway/logs:/app/logs
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
      auth-service:
        condition: service_started
      ticket-service:
        condition: service_started
      company-service:
        condition: service_started
      notification-service:
        condition: service_started
    networks:
      - ticketFlow-internal
      - ticketFlow-external



  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - ./auth-service/.env
    ports:
      - "4000:4000"
    container_name: ticketFlow-authService
    restart: unless-stopped
    volumes:
      - ./auth-service:/app
      - /app/node_modules
      - ./auth-service/logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - ticketFlow-internal



  company-service:   
    build: 
      context: ./company-service
      dockerfile: Dockerfile
    env_file:
      - ./company-service/.env
    container_name: ticketFlow-companyService
    restart: unless-stopped
    volumes:
      - ./company-service:/app
      - /app/node_modules
      - ./company-service/logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - ticketFlow-internal



  ticket-service:
    build: 
      context: ./ticket-service
      dockerfile: Dockerfile
    env_file:
      - ./ticket-service/.env
    container_name: ticketFlow-ticketService
    restart: unless-stopped
    volumes:
      - ./ticket-service:/app
      - /app/node_modules
      - ./ticket-service/logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - ticketFlow-internal


  communication-service:
    build: 
      context: ./communication-service
      dockerfile: Dockerfile
    env_file:
      - ./communication-service/.env
    container_name: ticketFlow-communicationService
    restart: unless-stopped
    volumes:
      - ./communication-service:/app
      - /app/node_modules
      - ./communication-service/logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - ticketFlow-internal


  subscription-service:
    build: 
      context: ./subscription-service
      dockerfile: Dockerfile
    env_file:
      - ./subscription-service/.env
    container_name: ticketFlow-subscriptionService
    restart: unless-stopped
    volumes:
      - ./subscription-service:/app
      - /app/node_modules
      - /app/src/generated
      - ./subscription-service/logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - ticketFlow-internal

  

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env
    container_name: ticketFlow-notificationService
    restart: unless-stopped
    volumes:
      - ./notification-service:/app
      - /app/node_modules
      - ./notification-service/logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - ticketFlow-internal


networks:
  ticketFlow-internal:
    driver: bridge
  ticketFlow-external:
    driver: bridge


volumes:
  rabbitmq_data:
  redis_data:
  loki-data:
  grafana-data:

