apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: ticketflow
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: shamnads306/ticketflow-notification-service:v1.0.3
        ports:
          - containerPort: 4200
        envFrom:
          - secretRef:
              name: notification-secret-env
        readinessProbe:
          httpGet:
            path: /health
            port: 4200
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 4200
          initialDelaySeconds: 20
          periodSeconds: 20
