apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ticketflow
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 4200
      targetPort: 4200
  type: ClusterIP
