apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: ticketflow
  labels:
    app: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
      - name: ticket-service
        image: shamnads306/ticketflow-ticket-service:v1.0.3
        ports:
          - containerPort: 4400
        envFrom:
          - secretRef:
              name: ticket-secret-env
        readinessProbe:
          httpGet:
            path: /health
            port: 4400
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 4400
          initialDelaySeconds: 20
          periodSeconds: 20
