apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  namespace: ticketflow
  labels:
    app: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
    - port: 4400
      targetPort: 4400
  type: ClusterIP
