apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ticketflow
  labels: 
    app: rabbitmq
  
spec:
  replicas: 1
  selector:
    matchLabes:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - containerPort: 5672
          - containerPort: 15672
        volumeMounts:
          - name: rabbitmq-storage
            mountPath: /var/lib/rabbitmq
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-data
  