apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ticketflow
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: shamnads306/ticketflow-api-gateway-service:v1.0.4
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: api-gateway-secret-env
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
