export const Messages = {
    SERVER_ERROR: "Internel server error",
    USER_BLOCKED: "Your are blocked from TicketFlow, Please contact support",
    USER_NOT_FOUND: "User not found !",
    USER_ALREADY_EXIST : "User with this email id is already exist",
    NO_ACCESS: "Unauthorized Access",
    INVALID_REQUEST: "Invalid request",
    ALL_FILED_REQUIRED_ERR : "Provide all required fields",
    FAIL_TRY_AGAIN : "Operation failed Try again !",
    DATA_NOT_FOUND : "Requested data not found !",
    FETCH_SUCCESS : "Data fetched successfully !" ,
    USER_STATUS_UPDATED : "Successfull user status got updated !",
    ENTER_VALID_INPUT : "Enter valid input !",
    DEPARTMENT_NAME_EXIST : "Department Name is already exist !",
    EMAIL_INVALID : "Email ID is invalid",
    IMAGE_UPDATED : "Image updated successfully",
    REQUIRED_FIELD_MISSING : "Required fields are missing",
    INPUT_INVALID_OR_FIELD_MISSING : "Given input is invalid or Required fileds are missing!",
    MSSG_SENDED : "Message sended successfully,",
    SOMETHING_WENT_WRONG : "something went wrogn try again !",
    DATA_FETCHED : "Data fetched successfully",
    PARTICIPIANTS_ID_MISSING : "Participiants id is missing" ,
  
  };
  