apiVersion: v1
kind: Service
metadata:
  name: company-service
  namespace: ticketflow
  labels:
    app: company-service
spec:
  selector:
    app: company-service
  ports:
    - port: 4100
      targetPort: 4100
  type: ClusterIP
