export const Messages = {
    SERVER_ERROR: "Internel server error",
    NO_ACCESS: "Unauthorized Access",
    INVALID_REQUEST: "Invalid request",
    ALL_FILED_REQUIRED_ERR : "Provide all required fields",
    FAIL_TRY_AGAIN : "Operation failed Try again !",
    DATA_NOT_FOUND : "Requested data not found !",
    FETCH_SUCCESS : "Data fetched successfully !" ,
    TICKET_STATUS_UPDATED : " Ticket status updated successfully !",
    ENTER_VALID_INPUT : "Enter valid input !",
    EMAIL_INVALID : "Email ID is invalid",
    REQUIRED_FIELD_MISSING : "Required fields are missing",
    DATA_CREATED : "data created successfully",
    FILE_UPDATED : "File updated successfully",
    INVALID_INPUT : "Enter valid Inputs fields",
    TICKET_REASSIGNED : 'Ticket re-assigned successfully!',
    TICKET_ID_MISSING : "Ticket id is missing !",
    TICKET_NOT_FOUND : "Ticket is not found !!",
    INVALID_FILED_OR_MISSING_FIELD : "Invalid fields or missing required fields !",
    ERROR_PUBLISH_MSSG :  "Error in publishing the message to queue !",
    CHANNEL_NOT_AVILABLE :  "Channle is not avilable",
    TICKET_CREATED : "Ticket Created successfully !",
    TICKET_DOC_ID_MISSING : "Ticket Document id is missing ! try again",
    UPDATE_FAILED : "Update failed ! try again",
    REOPEN_TICKET : "Only resolved ticket can be re-open",
    SOMETHING_WRONG : "Something went wrong ! please try again",
    REOPEN_SUCCESS  : "Ticket re-opened successfully !",
    REQ_EXIST : "The Request already exist ! try again",
    REQ_SUBMITED : "Request submitted successfully ! ",
    REQ_REJECTED : "Request reject successfully !",

  } as const;
  