apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ticketflow
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: shamnads306/ticketflow-auth-service:v1.0.3
        ports:
          - containerPort: 4000
        envFrom:
          - secretRef:
              name: auth-secret-env
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 20
          periodSeconds: 20
