apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ticketflow
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
