apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  namespace: ticketflow
  labels:
    app: communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
      - name: communication-service
        image: shamnads306/ticketflow-communication-service:v1.0.1
        ports:
          - containerPort: 4600
        envFrom:
          - secretRef:
              name: communication-secret-env
        readinessProbe:
          httpGet:
            path: /health
            port: 4600
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 4600
          initialDelaySeconds: 20
          periodSeconds: 20
