apiVersion: v1
kind: Service
metadata:
  name: communication-service
  namespace: ticketflow
  labels:
    app: communication-service
spec:
  selector:
    app: communication-service
  ports:
    - port: 4600
      targetPort: 4600
  type: ClusterIP
