apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: ticketflow
data:
  config.yaml: | 
    auth_enabled: false

    server:
      http_listen_port: 3100
      log_level: debug 

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_retain_period: 30s
      wal:
        enabled: true
        dir: /tmp/loki/wal  # Specify WAL directory

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_location: /tmp/loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /tmp/loki/chunks

    limits_config:
      retention_period: 48h

    chunk_store_config:
      max_look_back_period: 48h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 48h

    compactor:
      working_directory: /tmp/loki/compactor  
      shared_store: filesystem