apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  namespace: ticketflow
spec:
  selector:
    app: subscription-service
  ports:
    - protocol: TCP
      port: 4800
      targetPort: 4800
  type: ClusterIP
